services:
  - type: web
    name: pal-invoice-generator
    runtime: python3
    buildCommand: |
      apt-get update --fix-missing
      DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        chromium-browser \
        fonts-liberation \
        libgconf-2-4 \
        libxss1 \
        libxtst6 \
        libxrandr2 \
        libasound2 \
        libpangocairo-1.0-0 \
        libatk1.0-0 \
        libcairo-gobject2 \
        libgtk-3-0 \
        libgdk-pixbuf2.0-0
      apt-get clean
      rm -rf /var/lib/apt/lists/*
      pip install --no-cache-dir -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"